### ISSUE TITLE
Slight text issues

### ISSUE THREAD

**Issue by gregdeane** [wesbos/you-she#1]
Probably much too early for an issue (you are likely still putting the site together) so feel free to tell me to eff off. 😁

```text
...We believe in finding a home for your treasured pieces should not be restricted by the country as our friendship bonded across the Canada-US border. We would love to share our...
```
Seems like something got mixed up in the copy/paste.
<br/>

```text
Buying is simple and safe at Elle Marche!!
```
YouShe?

**Comment by wesbos** [comment]
Thanks, still working on it:)
